class CustomUtils:
    SUCCESSFUL = 1
    SOMETHING_WENT_WRONG = -1
    WRONG_CREDENTIALS = -2
    CUSTOMER_DOES_NOT_EXIST = -3
    ROOM_NOT_AVAILABLE = -4
    ROOM_WITH_GIVEN_NUMBER_ALREADY_EXIST = -5
    CUSTOMER_NOT_LOGGED_IN = -6
    EMAIL_SENDING_FAILED = -7
    CUSTOMER_WITH_EMAIL_NOT_EXIST = -8
    OTP_NOT_CORRECT = -9
    NO_BOOKINGS_EXIST = -10
    NO_CUSTOMERS_EXIST = -11
    ROOM_WITH_GIVEN_ID_DOES_NOT_EXIST = -12
    NOT_AUTHORIZED = -13
    INVALID_EMAIL = -14
    INVALID_CONTACT_NUMBER = -15
    INVALID_NAME = -16
    NEW_PASSWORD_SAME_AS_OLD_PASSWORD = -17
    DESCRIPTION_EMPTY = -18
    PASSWORD_TOO_SHORT = -19 


